[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "forest-analysis"
version = "0.1.1"
description = "--add description here--"
readme = "README.md"
license = { file = "LICENSE.md" }
authors = [
    { name = "Onnela Lab", email = "onnela.lab@gmail.com" }
]
dependencies = [
    "holidays",  # poplar
    "librosa",  # audio file durations in sycamore
    "numpy",
    "openrouteservice",
    "pandas",
    "pyproj",  # jasmine
    "pytz",  # jasmine, poplar
    "ratelimit",
    "requests",  # bonsai
    "scipy",
    "shapely",  # jasmine
    "ssqueezepy",  # oak
    "timezonefinder",  # poplar, bonsai
]
requires-python = ">=3.11"

[project.urls]
Homepage = "https://github.com/onnela-lab/forest"

[project.optional-dependencies]
dev = [
    "build",
    "flake8",
    "flake8-pytest-style",
    "mypy",
    "pytest",
    "pytest-mock",
    "twine",
    "types-python-dateutil",
    "types-pytz",
    "types-requests",
    "types-setuptools",
]

[tool.setuptools.packages.find]
include = ["forest*"]

[tool.setuptools.package-data]
"forest.poplar.raw" = ["noncode/*.csv", "noncode/*.json"]
